export const environment = {
  production: false,
  baseApiUrl: 'https://nm-api-express.onrender.com',
  bearerToken: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNiM2Y1NmM5NTI1NTNjNjRiNDJiODI3IiwibmFtZSI6IkRpbGFuZ2EgQWRtaW4iLCJ1c2VybmFtZSI6ImRpbGFuZ2FsYW5rZXNoYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImRpbGFuZ2EuYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjc1MDYwODc2LCJleHAiOjE2NzU2NjU2NzZ9.-XrkADiFn3JOmgCnogytoS3jNZZZ9sFj1n5CgsID8Lw',
};
